STAT_NAMES: dict[str, str] = {
                'air_damage_percent':'aDamPct',
                'air_damage_raw':'aDamRaw',
                'air_def':'aDef',
                'air_def_percent':'aDefPct',
                'air_melee_damage_percent':'aMdPct',
                'air_melee_damage_raw':'aMdRaw',
                'air_spell_damage_percent':'aSdPct',
                'air_spell_damage_raw':'aSdRaw',
                'agility':'agi',
                'agility_requirement':'agiReq',
                'allow_craftsman':'allowCraftsman',
                'attacktier':'atkTier',
                'average_dps':'averageDps',
                'critical_damage_percent':'critDamPct',
                'damage_percent':'damPct',
                'damage_raw':'damRaw',
                'defense':'def',
                'defense_requirement':'defReq',
                'dexterity':'dex',
                'dexterity_requirement':'dexReq',
                'elemental_damage_percent':'eDamPct',
                'elemental_damage_raw':'eDamRaw',
                'elemental_defense':'eDef',
                'elemental_defense_percent':'eDefPct',
                'elemental_melee_damage_percent':'eMdPct',
                'elemental_melee_damage_raw':'eMdRaw',
                'elemental_spell_damage_percent':'eSdPct',
                'elemental_spell_damage_raw':'eSdRaw',
                'elemental_steal':'eSteal',
                'exploding_damage':'expd',
                'fire_damage_percent':'fDamPct',
                'fire_damage_raw':'fDamRaw',
                'fire_defense':'fDef',
                'fire_defense_percent':'fDefPct',
                'fire_melee_damage_percent':'fMdPct',
                'fire_melee_damage_raw':'fMdRaw',
                'fire_spell_damage_percent':'fSdPct',
                'fire_spell_damage_raw':'fSdRaw',
                'fixed_id':'fixID',
                'heal_percent':'healPct',
                'hp':'hp',
                'hp_bonus':'hpBonus',
                'hp_regen_percent':'hprPct',
                'hp_regen_raw':'hprRaw',
                'id':'id',
                'intelligence':'int',
                'intelligence_requirement':'intReq',
                'jump_height':'jh',
                'knockback':'kb',
                'level_bonus':'lb',
                'life_steal':'ls',
                'level':'lvl',
                'main_attack_range':'mainAttackRange',
                'max_mana':'maxMana',
                'melee_damage_percent':'mdPct',
                'melee_damage_raw':'mdRaw',
                'mana_regen':'mr',
                'mana_steal':'ms',
                'neutral_damage_percent':'nDamPct',
                'neutral_damage_raw':'nDamRaw',
                'neutral_melee_damage_percent':'nMdPct',
                'neutral_melee_damage_raw':'nMdRaw',
                'neutral_spell_damage_percent':'nSdPct',
                'neutral_spell_damage_raw':'nSdRaw',
                'persistent':'persistent',
                'poison':'poison',
                'raw_damage_percent':'rDamPct',
                'raw_damage_raw':'rDamRaw',
                'raw_defense_percent':'rDefPct',
                'raw_melee_damage_percent':'rMdPct',
                'raw_melee_damage_raw':'rMdRaw',
                'raw_spell_damage_percent':'rSdPct',
                'raw_spell_damage_raw':'rSdRaw',
                'reflection':'ref',
                'spell_damage_percent':'sdPct',
                'spell_damage_raw':'sdRaw',
                'slots':'slots',
                'slow_enemy':'slowEnemy',
                'spell_cost_percent_1':'spPct1',
                'spell_cost_percent_2':'spPct2',
                'spell_cost_percent_3':'spPct3',
                'spell_cost_percent_4':'spPct4',
                'spell_cost_raw_1':'spRaw1',
                'spell_cost_raw_2':'spRaw2',
                'spell_cost_raw_3':'spRaw3',
                'spell_cost_raw_4':'spRaw4',
                'walk_speed':'spd',
                'sprint':'sprint',
                'sprint_regen':'sprintReg',
                'strength':'str',
                'strength_requirement':'strReq',
                'thunder_damage_percent':'tDamPct',
                'thunder_damage_raw':'tDamRaw',
                'thunder_defense':'tDef',
                'thunder_defense_percent':'tDefPct',
                'thunder_melee_damage_percent':'tMdPct',
                'thunder_melee_damage_raw':'tMdRaw',
                'thunder_spell_damage_percent':'tSdPct',
                'thunder_spell_damage_raw':'tSdRaw',
                'thorns':'thorns',
                'water_damage_percent':'wDamPct',
                'water_damage_raw':'wDamRaw',
                'water_defense':'wDef',
                'water_defense_percent':'wDefPct',
                'water_spell_damage_percent':'wSdPct',
                'water_spell_damage_raw':'wSdRaw',
                'weaken_enemy':'weakenEnemy',
                'xp_bonus':'xpb'}


def get_stat_indices() -> dict[str, int]:
    return {stat_name: index for index, stat_name in enumerate(sorted(STAT_NAMES.values()))}




def get_stat_pos(stat_name: str):
    stat_name_short = STAT_NAMES.get(stat_name)
    if stat_name_short is None:
        raise ValueError(f"Unknown stat name: {stat_name}")
    return STAT_INDICES[stat_name_short]

def get_stats_pos_list(stat_names: list[str]) -> list[int]:
    return [get_stat_pos(stat_name) for stat_name in stat_names]




STAT_INDICES: dict[str, int] = {
                'aDamPct': 0,
                'aDamRaw': 1,
                'aDef': 2,
                'aDefPct': 3,
                'aMdPct': 4,
                'aMdRaw': 5,
                'aSdPct': 6,
                'aSdRaw': 7,
                'agi': 8,
                'agiReq': 9,
                'allowCraftsman': 10,
                'atkTier': 11,
                'averageDps': 12,
                'critDamPct': 13,
                'damPct': 14,
                'damRaw': 15,
                'def': 16,
                'defReq': 17,
                'dex': 18,
                'dexReq': 19,
                'eDamPct': 20,
                'eDamRaw': 21,
                'eDef': 22,
                'eDefPct': 23,
                'eMdPct': 24,
                'eMdRaw': 25,
                'eSdPct': 26,
                'eSdRaw': 27,
                'eSteal': 28,
                'expd': 29,
                'fDamPct': 30,
                'fDamRaw': 31,
                'fDef': 32,
                'fDefPct': 33,
                'fMdPct': 34,
                'fMdRaw': 35,
                'fSdPct': 36,
                'fSdRaw': 37,
                'fixID': 38,
                'healPct': 39,
                'hp': 40,
                'hpBonus': 41,
                'hprPct': 42,
                'hprRaw': 43,
                'id': 44,
                'int': 45,
                'intReq': 46,
                'jh': 47,
                'kb': 48,
                'lb': 49,
                'ls': 50,
                'lvl': 51,
                'mainAttackRange': 52,
                'maxMana': 53,
                'mdPct': 54,
                'mdRaw': 55,
                'mr': 56,
                'ms': 57,
                'nDamPct': 58,
                'nDamRaw': 59,
                'nMdPct': 60,
                'nMdRaw': 61,
                'nSdPct': 62,
                'nSdRaw': 63,
                'persistent': 64,
                'poison': 65,
                'rDamPct': 66,
                'rDamRaw': 67,
                'rDefPct': 68,
                'rMdPct': 69,
                'rMdRaw': 70,
                'rSdPct': 71,
                'rSdRaw': 72,
                'ref': 73,
                'sdPct': 74,
                'sdRaw': 75,
                'slots': 76,
                'slowEnemy': 77,
                'spPct1': 78,
                'spPct2': 79,
                'spPct3': 80,
                'spPct4': 81,
                'spRaw1': 82,
                'spRaw2': 83,
                'spRaw3': 84,
                'spRaw4': 85,
                'spd': 86,
                'sprint': 87,
                'sprintReg': 88,
                'str': 89,
                'strReq': 90,
                'tDamPct': 91,
                'tDamRaw': 92,
                'tDef': 93,
                'tDefPct': 94,
                'tMdPct': 95,
                'tMdRaw': 96,
                'tSdPct': 97,
                'tSdRaw': 98,
                'thorns': 99,
                'wDamPct': 100,
                'wDamRaw': 101,
                'wDef': 102,
                'wDefPct': 103,
                'wSdPct': 104,
                'wSdRaw': 105,
                'weakenEnemy': 106,
                'xpb': 107,
}


if __name__ == "__main__":
    stat_indices = get_stat_indices()
    for stat_name, index in stat_indices.items():
        print(f"'{stat_name}': {index},")






